name: Display your favorite things

on: [push]

jobs:
    Display-your-favorite-things:
        runs-on: ubuntu-latest
        steps:
            - name: Give permission to execute the file
              run: chmod +x ./favorite_things.sh

            - name: Display your favorite things
              env:
                COLOUR: Blue
                FOOD: Arabian Food
                MOVIE: Action Movie
              run: ./favorite_things.sh  
              