name: Deploy EC2 server in AWS

on: [push]

jobs:
    Deploy-EC2-Server-in-AWS:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.6.0    
                
            - name: Initialize Terraform
              run: terraform init
              
            - name: Run Terraform Plan
              run: terraform plan

            - name: Run Terraform apply
              run: terraform apply -auto-approve  