name: Add 2 numbers using python

on: [push]

jobs:
    Add-2-number-using-python:
        runs-on: ubuntu-latest
        steps:
            - name: Add 2 numbers using python
              env:
                a: 35
                b: 26
              run: python ./sum.py  

