name: run shell commands

on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: run-shell-commands
              run: |
                pwd
                ls -ltr
                free -m